### ISSUE TITLE
为什么用管理员登陆后，使用getNotice得到的结果一直pending

### ISSUE THREAD

**Issue by Sun482** [Zephyrrro/mini-fresh-cup-frontend#8]
export const getNotice = () => {
  return request.get(`/user/getNotice`);
};
结果显示Promise { <state>: "pending" }
是哪里写错了吗

**Comment by Zephyrrro** [comment]
`await` 或者 `then` 去取 `Promise resolve` 的结果呢？

**Comment by Sun482** [comment]
额，改成下面这样就好了
getNotice().then(res => {
      console.log(res);
    });
